"""Build staged native icon resources. Never install, reserve live IDs, or patch the game.

Only container metadata is cloned from Potion. Raster art is generated by imagegen,
then technically normalized by IconAssetNormalize. No artistic image edit here.
"""
import argparse
from contextlib import closing
import hashlib
import json
from pathlib import Path
import shutil
import sqlite3
import struct
import subprocess

ROOT = Path(__file__).resolve().parents[1]
WORKSPACE = ROOT.parent
BASE = WORKSPACE / 'FFTModLoader_Prototype_v0.10.30/analysis-ff16tools-game-01040/sqlite/original-0004.sqlite'
CLI = WORKSPACE / 'FF16 Tools/win-x64/FF16Tools.CLI.exe'
PREVIEW = WORKSPACE / 'GenericKnights/dds-preview/bin/Debug/net9.0-windows/DdsPreview.dll'
REF = ROOT / 'art/native-reference/ui/ffto/icon'

def clone_parts(template, old_stem, new_stem):
    data = template.read_bytes()
    old, new = old_stem.encode(), new_stem.encode()
    if len(old) != len(new) or data.count(old) != 1:
        raise ValueError('Texture-part template requires exactly one equal-length stem.')
    result = data.replace(old, new)
    # Native offsets, logical sizes, name and all bytes except the stem stay intact.
    assert result.replace(new, old) == data
    assert struct.unpack_from('<III', result) == (32,12,1)
    return result

def stage_table(source, target, icon_id):
    with closing(sqlite3.connect(source.resolve().as_uri()+'?mode=ro',uri=True)) as db:
        schema = db.execute("SELECT sql FROM sqlite_master WHERE name='UIAbilityIcon'").fetchone()[0]
        rows = db.execute('SELECT * FROM UIAbilityIcon ORDER BY Key').fetchall()
        meta = db.execute("SELECT sql FROM sqlite_master WHERE name='_uniontypes'").fetchone()[0]
        unions = db.execute('SELECT * FROM _uniontypes ORDER BY id').fetchall()
    if len(rows) != 55 or {r[0] for r in rows} != set(range(55)):
        raise ValueError('Unexpected pristine ability-icon baseline.')
    if icon_id in {r[0] for r in rows}: raise ValueError('Refusing to replace a native icon.')
    potion = next(r for r in rows if r[0] == 24)
    with closing(sqlite3.connect(target)) as db:
        with db:
            db.execute(meta); db.executemany('INSERT INTO _uniontypes VALUES (?,?)', unions)
            db.execute(schema)
            db.executemany('INSERT INTO UIAbilityIcon VALUES (?,?,?)', rows+[(icon_id,*potion[1:])])
        assert db.execute('SELECT * FROM UIAbilityIcon WHERE Key<55 ORDER BY Key').fetchall()==rows

def main():
    p = argparse.ArgumentParser()
    p.add_argument('--normalized', type=Path, required=True)
    p.add_argument('--output', type=Path, required=True)
    p.add_argument('--item-id', type=int, default=261)
    p.add_argument('--ability-icon-id', type=int, default=55)
    a=p.parse_args(); out=a.output.resolve()
    if out.exists(): raise FileExistsError('Use a new staging folder.')
    if not 261<=a.item_id<=999 or not 55<=a.ability_icon_id<=999:
        raise ValueError('Candidate IDs must avoid originals and fit the audited three-digit stems.')
    out.mkdir(parents=True)
    records=[]
    for family,old,new,art,size in (
        ('equip_item','ei_240_uitx',f'ei_{a.item_id:03}_uitx','venom-flask.item.png',100),
        ('equip_item_s','ei_s_240_uitx',f'ei_s_{a.item_id:03}_uitx','venom-flask.item-small.png',48),
        ('ability','a_024_uitx',f'a_{a.ability_icon_id:03}_uitx','venom-flask.ability.png',96)):
        source=a.normalized/art
        # Validate PNG IHDR directly without changing any pixels.
        header=source.read_bytes()[:33]
        if header[:8]!=b'\x89PNG\r\n\x1a\n' or struct.unpack_from('>II',header,16)!=(size,size) or header[25]!=6:
            raise ValueError(f'Expected transparent RGBA {size}x{size}: {source}')
        folder=out/'resources/FFTIVC/data/enhanced/ui/ffto/icon'/family
        texture=folder/'texture'; parts=folder/'textureparts'
        texture.mkdir(parents=True); parts.mkdir()
        png=texture/(new+'.png'); shutil.copy2(source,png)
        subprocess.run([str(CLI),'img-conv','-i',str(png)],check=True,stdout=subprocess.DEVNULL)
        tex=png.with_suffix('.tex')
        part=parts/(new+'.utexpt')
        part.write_bytes(clone_parts(REF/family/'textureparts'/(old+'.utexpt'),old,new))
        qa=out/'qa'/family; qa.mkdir(parents=True)
        checked=qa/tex.name; shutil.copy2(tex,checked)
        subprocess.run([str(CLI),'tex-conv','-i',str(checked)],check=True,stdout=subprocess.DEVNULL)
        decoded=qa/(new+'.png')
        subprocess.run(['dotnet',str(PREVIEW),str(checked.with_suffix('.dds')),str(decoded)],check=True)
        # Converter emits lossless RGBA TEX from PNG; compare complete decoded pixel payloads.
        from PIL import Image
        with Image.open(source) as original, Image.open(decoded) as actual:
            if actual.size!=(size,size) or original.convert('RGBA').tobytes()!=actual.convert('RGBA').tobytes():
                raise ValueError('Native texture round trip changed RGBA pixels.')
        records.append(dict(Family=family,Texture=str(tex.relative_to(out)),TextureParts=str(part.relative_to(out)),
                            Dimensions=[size,size],TextureSha256=hashlib.sha256(tex.read_bytes()).hexdigest(),
                            ExactRgbaRoundTrip=True,NativePartGeometryPreserved=True))
    database=out/'ability-icons.sqlite'; stage_table(BASE,database,a.ability_icon_id)
    nxd=out/'resources/FFTIVC/data/enhanced/nxd'; nxd.mkdir(parents=True)
    subprocess.run([str(CLI),'sqlite-to-nxd','-i',str(database),'-o',str(nxd),'-g','fft'],check=True,stdout=subprocess.DEVNULL)
    if {f.name for f in nxd.iterdir()}!={'uiabilityicon.nxd'}: raise ValueError('Unexpected table output.')
    # Independent container round trip: all 55 original rows must remain byte-semantic identical.
    verify=out/'roundtrip.sqlite'
    subprocess.run([str(CLI),'nxd-to-sqlite','-i',str(nxd),'-o',str(verify),'-g','fft'],check=True,stdout=subprocess.DEVNULL)
    with closing(sqlite3.connect(database)) as expected,closing(sqlite3.connect(verify)) as actual:
        if expected.execute('SELECT * FROM UIAbilityIcon ORDER BY Key').fetchall()!=actual.execute('SELECT * FROM UIAbilityIcon ORDER BY Key').fetchall():
            raise ValueError('Ability-icon NXD round trip differs.')
    manifest=dict(SchemaVersion=1,IconKey='alchemist.venom-flask',Stage='NativeIconAssetsOnly',Installable=False,
        LiveIconIdsReserved=False,CandidateItemId=a.item_id,CandidateAbilityIconId=a.ability_icon_id,
        CandidateAbilityIconIdIsNotAbilityId=True,OriginalAbilityIconRowsPreserved=55,
        ExpandedAbilityIconRowCount=56,RequiredFullModAbilityIconRowCount=66,
        LiveResourceLoadingVerified=False,LegacyItemSpriteRouteReady=False,FullReworkedChemistReady=False,
        Notes=['IDs are staging candidates; reallocate against all enabled mods before integration.',
               'No ModConfig: this directory must not be installed as a playable mod.',
               'No native item/ability identities or original Potion resources are replaced.'],Resources=records)
    (out/'icon-assets.json').write_text(json.dumps(manifest,indent=2)+'\n',encoding='utf-8')
    print(f'PASS staged icons and native table: {out}; 55 original rows preserved; NOT installed.')

if __name__=='__main__': main()
