"""Build all eleven additive items/actions and game-native icon containers.

Art is generated by the integrated image tool and technically normalized by
IconAssetNormalize. No recoloring or artistic editing is performed here.
"""
import argparse, hashlib, json, shutil, sqlite3, struct, subprocess
from pathlib import Path
from contextlib import closing
from build_venom_content import ROOT, BASE, CLI, LOCALES, assert_same_tables, common_record
from build_venom_icons import clone_parts, PREVIEW, REF
from audit_native_layout import NativeImage, GAME, SUPPORTED_SHA256

STATUSES=[39,110,0,0,0,52,48,43,42,34,46]
TEMPLATES=[240,242,242,242,242,241,241,241,244,244,244]
def digest(p):return hashlib.sha256(p.read_bytes()).hexdigest().upper()
def run(*args):subprocess.run([str(x) for x in args],check=True,stdout=subprocess.DEVNULL)
def main():
    p=argparse.ArgumentParser();p.add_argument('--output',type=Path,required=True);a=p.parse_args()
    out=a.output.resolve()
    if out.exists() or not out.is_relative_to((ROOT/'builds').resolve()):raise ValueError('Use NEW build directory.')
    definition=json.loads((ROOT/'Alchemist.definition.json').read_text());actions=[x for x in definition['Actions'] if x.get('NewItem')]
    if len(actions)!=11:raise ValueError('Expected eleven extras.')
    image=NativeImage((GAME/'FFT_enhanced.exe').read_bytes())
    # Preserve the already user-validated Venom art/container exactly.
    prior=ROOT/'builds/venom-content-002'
    shutil.copytree(prior/'resources',out/'resources');shutil.copytree(prior/'native',out/'native')
    nxd=out/'resources/FFTIVC/data/enhanced/nxd'
    records=[]
    for idx,action in enumerate(actions):
        item,ability,icon=261+idx,513+idx,55+idx
        common=bytearray(common_record(image,action['PriceGil']))
        common[10]=1+4*(definition['Balance']['ShopUnlockChapters'][action['Key']]-1)
        (out/'native'/f"{action['Key']}.item-common.bin").write_bytes(common)
        (out/'native'/f"{action['Key']}.item-medicine.bin").write_bytes(bytes((107,definition['Balance']['FixedElementalDamage'],0)) if action['Effect']=='FixedElementalDamage' else bytes((56,0,STATUSES[idx])))
        if idx==0:continue
        normalized=ROOT/'art/full-v1'/action['Key']/'normalized'
        for family,old,new,suffix,size in (
            ('equip_item',f'ei_{TEMPLATES[idx]:03}_uitx',f'ei_{item:03}_uitx','item',100),
            ('equip_item_s','ei_s_240_uitx',f'ei_s_{item:03}_uitx','item-small',48),
            ('ability','a_024_uitx',f'a_{icon:03}_uitx','ability',96)):
            source=normalized/(action['Key']+'.'+suffix+'.png')
            from PIL import Image
            with Image.open(source) as im:
                if im.mode!='RGBA' or im.size!=(size,size) or im.getpixel((0,0))[3]!=0:raise ValueError('Invalid RGBA/transparency.')
            reference=(ROOT/'art/native-reference-extra/ui/ffto/icon'/family/'textureparts'/(old+'.utexpt')) if family=='equip_item' else REF/family/'textureparts'/(old+'.utexpt')
            folder=out/'resources/FFTIVC/data/enhanced/ui/ffto/icon'/family
            png=folder/'texture'/(new+'.png');shutil.copy2(source,png);run(CLI,'img-conv','-i',png)
            tex=png.with_suffix('.tex');parts=folder/'textureparts'/(new+'.utexpt')
            parts.write_bytes(clone_parts(reference,old,new))
            qa=out/'qa'/family;qa.mkdir(parents=True,exist_ok=True);checked=qa/tex.name;shutil.copy2(tex,checked)
            run(CLI,'tex-conv','-i',checked);decoded=checked.with_suffix('.png');run('dotnet',PREVIEW,checked.with_suffix('.dds'),decoded)
            with Image.open(source) as expected,Image.open(decoded) as actual:
                if expected.convert('RGBA').tobytes()!=actual.convert('RGBA').tobytes():raise ValueError('RGBA round trip failed.')
            records.append(dict(Key=action['Key'],Family=family,Dimensions=[size,size],ExactRgbaRoundTrip=True,NativePartGeometryPreserved=True,TextureSha256=digest(tex)))
            png.unlink() # packaging only TEX and UTEXPT, never unused conversion inputs
    dbroot=out/'databases';dbroot.mkdir()
    preserved={}
    for locale in LOCALES:
        dbpath=dbroot/f'venom.{locale}.sqlite'
        with closing(sqlite3.connect(BASE/f'original-0004.{locale}.sqlite')) as original,closing(sqlite3.connect(dbpath)) as target:
            with target:
                target.execute(original.execute("SELECT sql FROM sqlite_master WHERE name='_uniontypes'").fetchone()[0]);target.executemany('INSERT INTO _uniontypes VALUES (?,?)',original.execute('SELECT * FROM _uniontypes'))
                for family,template,count in [('Item',240,261),('Ability',368,512)]:
                    table=f'{family}-{locale}';target.execute(original.execute('SELECT sql FROM sqlite_master WHERE name=?',(table,)).fetchone()[0])
                    cols=[x[1] for x in original.execute(f'PRAGMA table_info("{table}")')];rows=original.execute(f'SELECT * FROM "{table}" ORDER BY Key').fetchall()
                    if len(rows)!=count:raise ValueError('Incomplete originals.')
                    placeholders=','.join('?' for _ in cols);target.executemany(f'INSERT INTO "{table}" VALUES ({placeholders})',rows)
                    base=dict(zip(cols,original.execute(f'SELECT * FROM "{table}" WHERE Key=?',(template,)).fetchone()))
                    for idx,action in enumerate(actions):
                        values=base.copy();name=action['Name'];key=action['Key'];effect=action.get('Status',action.get('Element'))
                        description=(f"Deals {definition['Balance']['FixedElementalDamage']} + {definition['Balance']['TargetMaxHpPercent']}% of target maximum HP as {effect.lower()} damage (rounded up), without Faith. Elemental modifiers apply." if action['Effect']=='FixedElementalDamage' else f'Inflicts {effect}, respecting status immunities.')
                        values.update(Key=(261 if family=='Item' else 513)+idx,DLCFlags=0,Name=name,Description=(description if family=='Item' else f'Consumes one {name.lower()}. {description} Range: 4.'),Comment='Reworked Chemist full v0.2.0; full-width additive identity.')
                        if family=='Item':values.update(NameSingular=name.lower(),NamePlural=name.lower()+'s',Name2=name,SortOrder=6017+idx)
                        else:values.update(IconId=55+idx,JpCost1=action['JpCost']&255,JpCost2=action['JpCost']>>8,IsRandomDamage=0,IsRandomStatus=0)
                        target.execute(f'INSERT INTO "{table}" VALUES ({placeholders})',tuple(values[c] for c in cols))
                    if target.execute(f'SELECT * FROM "{table}" WHERE Key<? ORDER BY Key',(count,)).fetchall()!=rows:raise ValueError('Original row changed.')
                    preserved[table]=count
        converted=out/'roundtrip'/locale;converted.mkdir(parents=True);run(CLI,'sqlite-to-nxd','-i',dbpath,'-o',converted,'-g','fft')
        checked=dbroot/f'venom.{locale}.roundtrip.sqlite';run(CLI,'nxd-to-sqlite','-i',converted,'-o',checked,'-g','fft');assert_same_tables(dbpath,checked)
        for f in converted.iterdir():shutil.copy2(f,nxd/f.name)
    icons=dbroot/'ability-icons.sqlite'
    with closing(sqlite3.connect(BASE/'original-0004.sqlite')) as source,closing(sqlite3.connect(icons)) as target:
        with target:
            for table in ['_uniontypes','UIAbilityIcon']:
                target.execute(source.execute('SELECT sql FROM sqlite_master WHERE name=?',(table,)).fetchone()[0]);rows=source.execute(f'SELECT * FROM {table}').fetchall()
                target.executemany(f'INSERT INTO {table} VALUES ({",".join("?" for _ in rows[0])})',rows)
            base=source.execute('SELECT * FROM UIAbilityIcon WHERE Key=24').fetchone()
            target.executemany('INSERT INTO UIAbilityIcon VALUES (?,?,?)',[(55+i,*base[1:]) for i in range(11)])
    run(CLI,'sqlite-to-nxd','-i',icons,'-o',nxd,'-g','fft')
    checked=dbroot/'ability-icons.roundtrip.sqlite';run(CLI,'nxd-to-sqlite','-i',nxd,'-o',checked,'-g','fft')
    with closing(sqlite3.connect(icons)) as expected,closing(sqlite3.connect(checked)) as actual:
        for table in ['_uniontypes','UIAbilityIcon']:
            if expected.execute(f'SELECT * FROM {table} ORDER BY 1').fetchall()!=actual.execute(f'SELECT * FROM {table} ORDER BY 1').fetchall():raise ValueError('Ability icon roundtrip failed.')
    plan=json.loads((ROOT/'analysis/playable-relocation-plan.json').read_text());plan.update(ReviewedFor='FullChemist15Actions',ActionCount=15,ExtraItemCount=11,OriginalGuardedOperandsUnchanged=True)
    (out/'native/playable-relocation-plan.json').write_text(json.dumps(plan,indent=2)+'\n')
    hashes={str(f.relative_to(out)):digest(f) for root in [out/'resources',out/'native'] for f in root.rglob('*') if f.is_file()}
    proof=dict(Stage='FullChemistContentIntegration',Installable=False,Actions=15,NewItems=11,ExecutableSha256=SUPPORTED_SHA256,PayloadHashes=hashes,Icons=records,NxdRoundTripVerified=True,OriginalRowsPreserved=preserved,GameplayTested=False)
    (out/'content-integration.json').write_text(json.dumps(proof,indent=2)+'\n')
    print(f'PASS: full 11-item/11-ability content, 30 new icon variants pixel-roundtripped, 7 locales: {out}')
if __name__=='__main__':main()
