<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks><TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AssemblyName>FFTModLoader.ReworkedChemist</AssemblyName>
    <DebugType Condition="'$(Configuration)' == 'Release'">none</DebugType>
    <PathMap>$(MSBuildProjectDirectory)=/_/ReworkedChemist</PathMap>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <FFTModLoaderSourceDirectory Condition="'$(FFTModLoaderSourceDirectory)' == ''">$(MSBuildThisFileDirectory)../../FFTModLoader_Prototype_v0.10.30</FFTModLoaderSourceDirectory>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="$(FFTModLoaderSourceDirectory)/src/ContentExpansionApi/ContentExpansionApi.csproj" />
    <PackageReference Include="Reloaded.Mod.Interfaces" Version="2.4.0" ExcludeAssets="runtime" />
  </ItemGroup>
</Project>
